### ISSUE TITLE
Cleaner Formatting of Copy/Paste of NR Logs

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#1444]
### Current Behavior

When copy/pasting the raw NR logs from FlowForge, I expect formatting to be consistent with the structure shown in FlowForge:

<img width="1727" alt="Screenshot 2022-12-15 at 14 44 08" src="https://user-images.githubusercontent.com/99246719/207890076-2e539ffa-d91a-4fbd-8afa-44eb53195019.png">

Instead, it pastes as:

```
13/12/2022 14:29:34
[info]
Welcome to Node-RED
===================
13/12/2022 14:29:34
[info]
Node-RED version: v3.0.2
13/12/2022 14:29:34
[info]
Node.js  version: v16.13.2
13/12/2022 14:29:34
[info]
Darwin 22.1.0 arm64 LE
13/12/2022 14:29:34
[info]
Loading palette nodes
13/12/2022 14:29:35
[warn]
------------------------------------------------------
13/12/2022 14:29:35
[warn]
[@flowforge/nr-file-nodes/file] 'file in' already registered by module node-red
13/12/2022 14:29:35
[warn]
[@flowforge/nr-project-nodes/project-link] Error: Project Link nodes cannot be loaded outside of flowforge EE environment (line:6)
13/12/2022 14:29:35
[warn]
------------------------------------------------------
13/12/2022 14:29:35
[info]
Settings file  : /Users/joepavitt/Documents/flowforge/development/flowforge/flowforge/var/projects/9b65d15b-4ab1-4b97-97fb-9ac5c0d228a3/settings.js
13/12/2022 14:29:35
[info]
Context store  : 'default' [module=memory]
13/12/2022 14:29:35
[info]
Server now running at http://127.0.0.1:12080/
13/12/2022 14:29:35
[warn]
Encrypted credentials not found
13/12/2022 14:29:35
[info]
Starting flows
13/12/2022 14:29:35
[info]
Started flows
15/12/2022 14:41:37
[]
15 Dec 14:41:37 - [red] Uncaught Exception:
15/12/2022 14:41:37
[error]
HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/Users/joepavitt/Documents/flowforge/development/flowforge/flowforge/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
15/12/2022 14:41:37
[system]
Node-RED exited rc=1 signal=null
15/12/2022 14:41:37
[system]
Starting Node-RED
15/12/2022 14:41:37
[error]
Failed to start server:
15/12/2022 14:41:37
[error]
HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/Users/joepavitt/Documents/flowforge/development/flowforge/flowforge/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Expected Behavior

The pasted content should format nicely, with the date/type/info all on the same line

### Steps To Reproduce

Copy & paste the contents from the `/project/<project-id>/logs` window into a text editor or Slack.

### Environment

- FlowForge version: `main`
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by AllanOricil** [comment]
I will take a look at this.
