### ISSUE TITLE
Pallete Manager UI not installed the dependencies and crashed after trying to start

### ISSUE THREAD

**Issue by Anmirazik** [FlowFuse/flowfuse#3237]
### Current Behavior

12/20/2023 11:45:04 AM
[info]
Node-RED version: v3.1.3
12/20/2023 11:45:04 AM
[info]
Node.js  version: v18.19.0
12/20/2023 11:45:04 AM
[info]
Linux 5.4.247-162.350.amzn2.aarch64 arm64 LE
12/20/2023 11:45:09 AM
[info]
Loading palette nodes
12/20/2023 11:45:10 AM
[system]
Node-RED health check failed: RequestError: connect ECONNREFUSED 127.0.0.1:1880 (http://127.0.0.1:1880/)
12/20/2023 11:45:11 AM
[info]
FlowFuse HTTP Authentication Plugin loaded
12/20/2023 11:45:11 AM
[info]
FlowFuse Team Library Plugin loaded
12/20/2023 11:45:11 AM
[info]
FlowFuse Light Theme Plugin loaded
12/20/2023 11:45:11 AM
[info]
FlowFuse Dark Theme Plugin loaded
12/20/2023 11:45:12 AM
[info]
FlowFuse Metrics Plugin loaded
12/20/2023 11:45:17 AM
[system]
Node-RED health check failed: RequestError: connect ECONNREFUSED 127.0.0.1:1880 (http://127.0.0.1:1880/)
12/20/2023 11:45:19 AM
[]
20 Dec 03:45:19 - [red] Uncaught Exception:
12/20/2023 11:45:20 AM
[error]
**TypeError: Cannot read properties of undefined (reading 'enabled')
    at refreshDirectories (/data/node_modules/node-red-contrib-flow-manager/flow-manager.js:418:46)
    at startFlowManager (/data/node_modules/node-red-contrib-flow-manager/flow-manager.js:753:15)
    at main (/data/node_modules/node-red-contrib-flow-manager/flow-manager.js:789:11)
    at module.exports (/data/node_modules/node-red-contrib-flow-manager/flow-manager.js:1102:5)
    at loadNodeSet (/usr/src/node-red/node_modules/@node-red/registry/lib/loader.js:359:27)
    at /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js:453:31
    at Array.forEach (<anonymous>)
    at loadNodeSetList (/usr/src/node-red/node_modules/@node-red/registry/lib/loader.js:448:11)
    at /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js:145:16**
12/20/2023 11:45:20 AM
[system]
Node-RED exited rc=1 signal=null
12/20/2023 11:45:20 AM
[system]
Node-RED unexpectedly stopped after: 25s
12/20/2023 11:45:20 AM
[system]
Node-RED restart loop detected whilst in safe mode. Stopping.

### Expected Behavior

Hi Im facing this issue after adding "Installed Modules" through the Flowfuse Cloud UI , i tried to install **node-red-contrib-flow-manager** through the UI table but the above error occurs , i thought after adding the modules in the UI tables, it will installed automatically ?  I also tried installing using the flows editor and the same error occurs

### Environment

- FlowForge version: Cloud Version
- Node.js version: 18.19.0
- npm version: 
- Platform/OS: Flowfuse Cloud 
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Anmirazik** [comment]
i found that this issues are regarding with the library itself since i tried to install other library it works , i think i can close this issue now
