### ISSUE TITLE
Improve FF eeror reporting with missing stack / spinning up a project

### ISSUE THREAD

**Issue by sherbastian** [FlowFuse/flowfuse#3670]
### Current Behavior

Current log state:

```shell
[2024-04-02T12:27:35.030Z] INFO: Starting project be7a6f6c-a189-4561-b61f-dbe12336c2e6 on port 12081
[2024-04-02T12:27:35.147Z] INFO: Set FORGE_NR_PATH to /home/cstns/Workspace/flowfuse/var/stacks/1.2.3
RequestError: connect ECONNREFUSED 127.0.0.1:13081
    at ClientRequest.<anonymous> (/home/cstns/Workspace/flowfuse/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.emit (node:domain:489:12)
    at origin.emit (/home/cstns/Workspace/flowfuse/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  code: 'ECONNREFUSED',
  timings: {
    start: 1712060866148,
    socket: 1712060866148,
    lookup: 1712060866148,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1712060866150,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 0,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 2
    }
  }
}
```

N.B.
notice the different port mappings 12080 & 13080

### Expected Behavior

We should be able to detect that a stack has not been installed

### Steps To Reproduce

In FF UI, create a stack for a NR  version that you don't have installed

### Environment

- FlowFuse version: latest@dev
- Node.js version: 18.15.0
- npm version: N/A
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
For context on the differing port numbers, the localfs driver runs the `nr-launcher` app on one port, which then runs node-red itself on another port. The forge app communicates with the instance via the `nr-launcher` process.

This error is because the forge app hasn't been able to communicate with the launcher process. The challenge here is we don't know *why* the launcher isn't responding. A missing stack is just one possible reason.

I suspect (but don't know for sure) that the launcher logs would have reported something more useful - but if the forge app cannot query the launcher, then we can't get that information back to the frontend.
