### ISSUE TITLE
Crash in DeviceTunnelManager

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#3736]
### Current Behavior

Seen in production:

```
{"level":"INFO","time":"2024-04-16T02:04:05.284Z","msg":"Device 0ag8pP0gN5 tunnel id:10135 - new editor connection req:1 "}
TypeError: Cannot read properties of undefined (reading 'send')
    at WebSocket.<anonymous> (/usr/src/forge/app/node_modules/@flowfuse/flowfuse/forge/ee/lib/deviceEditor/DeviceTunnelManager.js:282:31)
    at WebSocket.emit (node:events:529:35)
    at WebSocket.emit (node:domain:489:12)
    at Receiver.receiverOnMessage (/usr/src/forge/app/node_modules/ws/lib/websocket.js:1209:20)
    at Receiver.emit (node:events:517:28)
    at Receiver.emit (node:domain:489:12)
    at /usr/src/forge/app/node_modules/ws/lib/receiver.js:608:16
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
```

I think this is a timing issue where a proxied request has arrived around the same time the device has disconnected and we've nulled the socket.

Going to add some guards around the socket usage.

### Expected Behavior

No crashes

### Steps To Reproduce

Its a timing issue we've seen once in production in the last few weeks. It'll take longer to reproduce than it will to fix.

### Environment

- FlowFuse version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
As this was closed before we had `deploy:pr` fully up and running, want to make sure this has been fully verified before closing - @knolleary can you do the honours please?

**Comment by knolleary** [comment]
We could not readily reproduce this as it is a hard to hit timing window we have seen a small number of times in production. Given the nature of the change, I'm happy to mark this verified. If we see the crash again, we can reopen and reinvestigate.
