### ISSUE TITLE
50% kebab menu actions on  device in Applications -> devices do not work

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#4248]
### Current Behavior

"Remove from Application" and "Delete Device kebab" menu actions not working  on  device in Applications -> Devices

![chrome_wjmjiItKaO](https://github.com/user-attachments/assets/5e8448e3-9f3e-443d-91e1-fa6604b3aa9b)

I suspect this is related to: https://github.com/FlowFuse/flowfuse/issues/4246#issue-2427974312

### Expected Behavior

All actions should work

### Steps To Reproduce

Visit devices of an application

### Environment

- FlowFuse version: 2.6.x Live (PROD)
- Node.js version:
- npm version:
- Platform/OS:
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
Getting error: 
![image](https://github.com/user-attachments/assets/54300183-3c9e-42f3-b9f3-2d8dae7f06e9)

```
TypeError: Cannot read properties of undefined (reading 'show')
    at Object.show (dialog.js:42:12)
    at Proxy.deviceAction (DeviceActions.js:100:69)
    at onClick (DevicesBrowser.vue?./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/dist/templateLoader.js??ruleSet%5B1%5D.rules%5B2%5D!./node_modules/vue-loader/dist/index.js??ruleSet%5B1%5D.rules%5B10%5D.use%5B0%5D:180:31)
    at callWithErrorHandling (runtime-core.esm-bundler.js:338:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:345:17)
    at HTMLLIElement.invoker (runtime-dom.esm-bundler.js:857:82)
```

**Comment by Steve-Mcl** [comment]
@joepavitt I assigned you this one as discussed on Slack

Repro to follow...

**Comment by Steve-Mcl** [comment]
1. Open Dev Tools -> console
2. Visit An instance -> Snapshots -> click a snapshot kebab -> click delete
   a. Should work (just cancel, dont delete)
2. Visit Applications -> devices.
4. Click a device kebab -> delete
   a. Should get error 
5. Now revisit An instance -> Snapshots -> click a snapshot kebab -> click delete
   a.  Now getting same dialog show error
   b. Also, other places throughout the App do this wherever we use the reusable dialog


Video demo posted in slack
