### ISSUE TITLE
Rare unit test failure in Device API

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#866]
A couple times the postgres unit tests have hit the following failure:
```
  1) Device API
       Device Checkin
         device downloads settings:
     AssertionError: expected null to be '483be6b1bb5be1321f62f2d8f56884b14f9db2b7895a0ed71a118b4e62dc9318'
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (test/unit/forge/routes/api/device_spec.js:593:53)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

As the tests pass 99% of the time, this must be a timing window either in the test case or the platform code.

Possibly an async action not being awaited.

I think it is unlikely to be hit in production when the APIs are being driven at human speed, but we should track down and tidy up nonetheless.

**Comment by knolleary** [comment]
This issue has gotten very rare - not seen it for a while and walking the code I don't immediately see any obvious bits missing.

Going to close this for now.

**Comment by knolleary** [comment]
Reopening as we've seen another one-off test failure. Not the same test, but in the device checkin area.

```
 1) Device API
       Device Checkin
         device checks in with a valid snapshot and settingsHash:

      AssertionError: expected 409 to be 200
      + expected - actual

      -409
      +200
      
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (test/unit/forge/routes/api/device_spec.js:563:40)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by knolleary** [comment]
Closing as we haven't see this for a long time
